"""add business profiles

Revision ID: 015d7b1f7bdb
Revises: 0632cbc850ef
Create Date: 2026-10-01 14:53:02.131281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '015d7b1f7bdb'
down_revision: Union[str, Sequence[str], None] = '0632cbc850ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('business_number', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('business_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('business_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('business_status_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tax_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tax_type_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('end_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('verification_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('business_profiles')
    # ### end Alembic commands ###
